### ISSUE TITLE
In Tableau 2019.2 set actions cause the extensions to reload it's content

### ISSUE THREAD

**Issue by bggoxp** [tableau/extensions-api#240] opened 2019-06-24 11:15 UTC
Hello,

We got a report stating that when using set actions with Tableau 2019.2 this was causing issues with the usage of our extensions.
I looked into this and what is happening is that every click on the marks that trigger the set action also trigger a reload on the extension frame causing it to lose its context or content. In our case, we have a login token and it is lost, making it so that we have to login every time the extension reloads.

Have you ever come up with this, is a known issue or is there any way to prevent the extension from reloading?

Best regards,
Bruno

**Comment by Kovner** [comment] 2019-06-25 23:04
Hrmm, we have a report of this happening when using Parameter Actions and we have some scheduled work to understand the cause of that and fix it. I will add set actions as something to explore as well.

**Comment by johnDance** [comment] 2019-06-25 23:56
I did some testing with Set Actions. I used the example described here:
https://onlinehelp.tableau.com/current/pro/desktop/en-us/actions_sets.htm#color-scaling

Using this set action, the extension does not get reloaded. Can you share more about your workbook or actions? Do you have other actions on the dashboard? I'm assuming you are using server?

Thanks for the additional information,
John

**Comment by bggoxp** [comment] 2019-06-27 08:44
Hello John.

I'm doing it on the desktop version.
I tested in that example as well, and indeed it does not trigger a reload.

The example that I was using was the asymmetric drill down (available [here](https://www.tableau.com/learn/tutorials/on-demand/set-actions)), and there, whenever selecting a mark for drill down a refresh is performed.

Thanks,
Bruno

**Comment by johnDance** [comment] 2022-12-29 15:46
The issue with the asymmetric drill down example is that changes the data source / summary data without any notification to the extension, so we must reload. We need to add a "summary data changed" notification, but need to figure out how to do that without breaking existing extensions.

**Comment by johnDance** [comment] 2022-12-29 15:49
See also https://github.com/tableau/extensions-api/issues/167

**Comment by johnDance** [comment] 2022-12-29 17:15
I'm going to close this one as we track 167 and 368.

**Closed by johnDance** 2022-12-29 17:15 UTC
Labels: Duplicate, Enhancement
