### ISSUE TITLE
Summary data column data type returns nothing but strings

### ISSUE THREAD

**Issue by craigbloodworth** [tableau/extensions-api#121] opened 2018-05-22 11:19 UTC
`sheet.getSummaryDataAsync({ignoreSelection: true}).then((data) => {`

The column meta data contained in data.columns[i] has the attribute **dataType** which presumably is supposed to return string, float, int, date, etc.

However it seems to always be returning the value 'string' even when it's obviously not a string type:
![image](https://user-images.githubusercontent.com/8116300/40359353-5959a3e8-5dba-11e8-9ad3-69cd532881d4.png)

**Comment by johnDance** [comment] 2018-05-22 16:27
Hi Craig: 
Thanks for your report. We have fixed this in house. It should be fixed in the next beta update. Thanks for working with extensions. We are excited to see what developers are building.
John

**Comment by elatt** [comment] 2018-06-21 17:40
I think this is a duplicate of #41. Is the `GetUnderlyingDataAsync()` call fixed as well?

**Comment by KeshiaRose** [comment] 2019-02-07 17:43
Yes, both are fixed in 2018.2.

**Closed by KeshiaRose** 2019-02-07 17:43 UTC
Labels: 2018.2, Logged Internally, duplicate
