### ISSUE TITLE
Extension freezes when navigating between sheets/dashboards, or duplicating dashboard

### ISSUE THREAD

**Issue by telekineticyeti** [tableau/extensions-api#377] opened 2021-04-13 10:10 UTC
My team and I developed a custom visual using the latest version (1.4) of the extensions API SDK. 

The visual works well in most environments, with the exception of Tableau Desktop for Windows. 

In Windows desktop, the visual freezes occasionally when navigating between sheets and dashboards. It will also freeze consistently when duplicating a dashboard.

While we originally thought that this was an issue with our visual, we have found that it happens to any custom visual that has been loaded onto the dashboard.

Here are the steps for reproduction:

1. Create a sheet, then create a dashboard
2. Add a custom visual to the dashboard
3. Duplicate the dashboard

The visual in the duplicated dashboard can still be interacted with, however the same visual in the original dashboard will be completely frozen.

The frozen visual can be unfrozen by resizing the visual frame.

This has been reproducible by us in the following versions of Tableau Desktop for Windows: 2020.1.3, 2020.4.1, 2021.1

My question is: are there any possible workarounds to making the visual responsive again, or reset the rendering of the visual frame?

Here are some things that we tried, but did not work:
- Using an older version of the extensions API
- Dispatching various events from within the visual frame. This did not seem to affect anything visually, however we did note that events and API calls were still working in the visual frame despite the visual rendering remaining frozen.

**Comment by johnDance** [comment] 2021-04-13 17:20
Thank you Paul. Using your good report, we were able to duplicate the issue in-house. It turns out that it is caused by our upgrade to the latest version of QWebEngine/Chromium. We have reported the issue to the team responsible. Unfortunately, the only workaround at the moment is to resize your dashboard. :-( 
John

**Comment by telekineticyeti** [comment] 2021-04-13 17:34
Hi John, thank you very much for the confirmation and for forwarding the issue on! 

Kindest regards,

Paul

**Comment by bggoxp** [comment] 2021-07-06 10:33
Hi everyone,

I was just about to open an issue on this as well, we recently started noticing this in Tableau 2021.1 and 2021.2 as well but came across this git hub issue. 

I recorded a small video showing how I can recreate this with tableau 2021.2 and also a comparison with 2019.3 where the issue did not seem to happen.

https://youtu.be/ZBnLGY1fmN4

As @telekineticyeti was saying, when navigating between certain parts, it causes the extensions to freeze.

And as @johnDance suggested, resizing the dashboard does indeed "unlock" the extensions, which is very odd.

From what I can see, and it seems that it matches what @telekineticyeti said, the extensions seem to be running and working (I was able to debug this with the Write-Back extension that we develop) but despite them running, the visuals are not updated at all; we can see that the ones that have dialogs, the dialog still opens, but the visuals on the dashboard do not update, and if the extension has any input field, they become unresponsive as well. 

After resizing, just like John suggested, I noticed that the inputs even have the values that I tried to input when the visuals were frozen.

Do you have any updates on this? Should I also open an issue on the tableau side or just here on GitHub?

Best regards,
Bruno

**Comment by johnDance** [comment] 2021-09-10 21:17
Hi Bruno
Sorry for the long delay. We converted our email system, and the notification got buried in my inbox. 
Unfortunately we don't have any updates on this. We have an internal defect tracking this.
Thank you,
John

**Comment by bggoxp** [comment] 2021-09-14 08:42
Hi @johnDance,

Thank you for the update. I'll be on the look out for this.

BR,
Bruno

**Comment by Tubulidentata** [comment] 2022-03-16 06:31
Good to know, that this will be fixed in the 2022.2 version. Its better to communicate that, than "there will be a fix soon™"

Thank you for fixing this, and for your fast response
Jan

**Closed** 2022-10-06 17:04 UTC
Labels: Bug, Fixed, 2022.2
