### ISSUE TITLE
selectMarksByValueAsync doesn't work with Measure Names and Measure Values fields

### ISSUE THREAD

**Issue by bartoszZamojcinRoche** [tableau/extensions-api#443] opened 2021-12-22 10:54 UTC
Hello,

when I am trying to select marks by selectMarksByValueAsync method on Worksheet object using Measure Names or Measure Values as field name nothing happens and marks are not selecting.

Bartosz

**Comment by johnDance** [comment] 2022-02-05 00:41
Thank you @bartoszZamojcin 

We have duplicated the issue internally and found that Measure Names and Measure Values are improperly handled by internals in selection handling. We have narrowed down the issue and found a root cause. I created a defect and assigned it to the selections team. I have also reported that it is a blocking issue for you. 

Thank you,
John

**Comment by johnDance** [comment] 2022-02-05 00:42
Internal defect is #1372577.

**Comment by johnDance** [comment] 2022-03-16 22:08
Good news @bartoszZamojcin
The selections team has fixed this. I have verified that I can use selectMarksByValueAsync on both Measure Names and Measure Values. This will be released in version 2022.2.
John

**Comment by bartoszZamojcinRoche** [comment] 2022-04-07 10:45
@johnDance 
Thanks for dealing with the issue. When can we expect version 2022.2 to be released?

Bartosz

**Comment by johnDance** [comment] 2022-04-13 16:17
Normally it is at the end of that quarter. So for .2, it would be right around the end of June.

**Comment by bartoszZamojcinRoche** [comment] 2022-04-26 10:04
@johnDance
Unfortunately within our organization we wont get version 2022.2 this year, but instead it will be 2022.1, so the fix wont affect us. Is there any way to backport the solution to the version 2022.1 like you proposed in one of the other issues? This would be highly appreciated.

Bartosz

**Closed** 2022-10-06 17:05 UTC
Labels: Bug, Fixed, 2022.2
