### ISSUE TITLE
Enable WebGL

### ISSUE THREAD

**Issue by ed-gonzalez** [tableau/extensions-api#149] opened 2018-08-21 13:47 UTC
Please enable WebGL or provide switch to enable by user.

I Would like to include advanced graphics created with WebGL as well as reference libraries such as deck.gl which generates maps using WebGL.  

It looks like the embedded browser in the extension object is using chrome 49 and needs to have WebGL enabled.  However the web page object seems to be using safari, and WebGL is working there.

![tbleaubrowser](https://user-images.githubusercontent.com/10732496/44405311-ed195200-a526-11e8-9f9a-49a354242e1a.png)
 is enabled there.

**Comment by johnDance** [comment] 2018-10-17 20:30
Hello Ed:
We are planning on supporting WebGL in extensions, but there are some challenges to overcome. I can't promise a date, but it is a high priority for us.
John

**Comment by jerryhall** [comment] 2019-02-16 23:41
Any update on this? I'm trying to use the MapAnalytics extension to no avail (JavaScript Alert, demos.mapbox.com, 'This extension is not currently supported on Windows'. On the extension site they suggest it could work, well, that 'a known issue that affects some users on Tableau Desktop for Windows' from here: https://docs.mapbox.com/geographic-analytics/overview/ Any ideas how I might use this (what would be a very useful) tool?  I'm on Windows 7, Dell i7, 16gb mem, using Tableau 2018.3.2. Thanks!

**Comment by johnDance** [comment] 2019-02-19 16:33
Hi Jerry
I have good news and bad news. The good news is that we have enabled WebGL on the Macintosh. The bad news is that this doesn't help you at all. I am sorry. We have run into issues with contention between WebGL and our hardware enabled rendering pipeline. The challenges have changed since October, but the outcome has not. We have not dropped the task, but we need to focus on a few other things first.
John

**Comment by aybbr** [comment] 2019-03-16 23:53
Hey,

I recently updated my Tableau Desktop version to 2019.1 and MapAnalytics stopped working. Same WebGL issue. 'Failed to initialize Mapbox extension! Error: Failed to initialize WebGL'
Any idea how can I overcome this?

**Comment by johnDance** [comment] 2019-03-20 16:34
Hi!
This has been fixed in the 2019.1.1 update, (and 2019.2 when it comes out).
John

**Comment by 9squirrels** [comment] 2019-03-27 05:32
Hi, is there any update on this issue and when it's likely to be resolved for Windows users?

**Comment by illonage** [comment] 2019-03-28 17:55
Hi @9squirrels, the team is working on it but we don't have a timeline for it. We will keep updated. Thanks, Geraldine

**Comment by m4328sfda9** [comment] 2019-09-11 14:14
Hi - is there any timeline for when Mapbox extensions/WebGL will be available for Tableau Desktop for windows?  Thanks!

**Comment by LuizMBR** [comment] 2019-12-09 22:43
Any updates on this?

**Comment by Kovner** [comment] 2019-12-10 00:32
Unfortunately we haven't had the bandwidth to put much work on this yet. We have an idea of what we need to do, but that's all we can say at this point. I'm sorry!

**Comment by pSeeper** [comment] 2020-03-10 14:48
Hi, 

Is there an update in the issue?

What workaround exists?

**Comment by Kovner** [comment] 2020-03-10 16:51
Hi @pSeeper I'm sorry there is no update at this time. We haven't had the chance to put in any work on this recently. The only workarounds are to use Server web authoring or Mac Desktop.

**Comment by JD-Franco** [comment] 2020-06-17 20:48
Any updates on this?

It is a shame that mapboxgl based extensions won't work on PCs.

Any idea when this would be solved?

**Comment by johnDance** [comment] 2020-07-31 00:08
I'm afraid the road to that is harder than it should be. We are focused on some other areas right now.
Hopefully in 2021.
Sorry. :-(
John

**Comment by iottester123** [comment] 2021-05-25 20:23
Hi @johnDance, do you have any updates on this fix?

**Comment by johnDance** [comment] 2021-05-29 02:18
Hi @iottester123
This is one of those cases where the quote "It hurts too much to laugh, but I'm too old to cry" might apply.

Underneath desktop, we use Chromium and QWebEngine as our web client. On Windows, Chromium uses ANGLE for its openGL (and therefore) WebGL implementation. ANGLE is not thread safe. Chromium doesn't have an issue with this because all rendering is handled with a single GPU scheduling thread, but Tableau has a different rendering thread model. We were hoping a new version of QWebEngine would solve this problem, but it did not. 

We will be investigating some a software rendering solution for openGL/WebGL and see if is performant enough.
Sorry for the continued bad news.
John

**Comment by KCPKCP** [comment] 2022-06-30 04:24
Hi @johnDance 

Are there any new updates on this..?  I'm using Tableau Desktop 2021.4.8

**Comment by johnDance** [comment] 2022-07-06 14:25
Hello @KCPKCP 
Unfortunately no. Sorry.
John

**Comment by johnDance** [comment] 2022-10-06 17:44
Duplicate of https://github.com/tableau/extensions-api/issues/378.

**Closed** 2022-10-06 17:45 UTC
Labels: Duplicate, Enhancement
