### ISSUE TITLE
[bug] [2018.2] filter-changed event not firing if filter was added from another sheet

### ISSUE THREAD

**Issue by tjallingt** [tableau/extensions-api#143] opened 2018-08-09 10:14 UTC
It looks like indirectly applied filters are not triggering the filterchanged event on sheets.

![filter-bug](https://user-images.githubusercontent.com/5736783/43892814-4c558f9e-9bcd-11e8-996c-b75d616ac40e.gif)

Sheet 1 is the sheet i'm listening to filter-changed events on.
filter `1 (sheet 1)` was created by adding a filter from sheet 1 and `1 (sheet 2)` was created by adding it from sheet 2.

By adding from I mean using this button on the respective sheet:

![untitled](https://user-images.githubusercontent.com/5736783/43892975-c55b674c-9bcd-11e8-9e90-236dc8f45f6c.png)

EDIT:

just to be clear: both filters are set to "apply to worksheets > all using this datasource"

**Comment by merlijnbuit** [comment] 2018-12-13 11:19
Any updates?

**Comment by johnDance** [comment] 2018-12-18 17:16
Hi. Thanks for the report. Is this happening on desktop or server/online, or everywhere? I am currently working on a related issue (https://github.com/tableau/extensions-api/issues/179), but that is a server/online issue.

**Comment by tjallingt** [comment] 2018-12-18 17:54
Was tested on desktop... I don't remember testing it on server so I'm not sure. Ill try it out tomorrow ;)

**Comment by tjallingt** [comment] 2018-12-19 10:57
Tested on the tableau online developer preview (2019.1 beta) and it also happens there, so I think it's safe to assume this is happening everywhere.

Wild speculation: this seems to be caused by the extension only receiving filter changed events that are sourced from the worksheet the event listener is attached to, instead of all filter changed events targeting that worksheet.

**Comment by tjallingt** [comment] 2019-06-12 08:47
@johnDance This is still happening in 2019.2 (on Server and Desktop):
![bug](https://user-images.githubusercontent.com/5736783/59336403-c9660900-8cfe-11e9-8cd3-b0babccfabf8.gif)

- Extensions (tables on the right) are reading data (and listening to filter-changed events) from the sheet on their left.
- Filter on Segment was added to the dashboard from the dropdown menu of the top left sheet (Sheet 3).
- Filter on Segment was set to "filter all using this datasource"
- Extension on the top re-reads the summarydata because it received a filter changed event, extension on the bottom does not.

**Comment by johnDance** [comment] 2019-06-13 21:38
The good news is that we have fixed this internally. It will be part of 2019.3!

**Comment by tjallingt** [comment] 2019-07-01 07:41
I downloaded the 2019.3 prerelease and can confirm it fixes this issue. Thanks

**Closed** 2019-07-01 07:41 UTC

**Comment by SiebeG** [comment] 2020-06-15 16:36
Hi @johnDance 

You may have to re-open this ticket/issue since Tableau Server (Tableau Online) does not register the dashboard action when you use the GoTo Dashboard action before it redirects to the new dashboard/sheet. We store the event of the dashboard action but it never gets stored because the GoTo action will have the user leave the dashboard and the extension does not get the important event of the dashboard action.

I can confirm it works in Tableau Desktop (2019.3 and higher) but on tableau Server the registration of the selection doe snot take place. I tested in all versions up to 2020.2 (Tableau Online) and i cannot get the dashboard action to be registered before the GoTo sheet/dashboard action will redirect to the new dashboard/sheet.

**This is an urgent issue for us since one of our clients has indicated not to continue their subscription on the extension if this will not be fixed.**
