### ISSUE TITLE
applyFilterAsync throws error when applying values for Measure Names filter

### ISSUE THREAD

**Issue by bartoszZamojcinRoche** [tableau/extensions-api#444] opened 2021-12-22 11:15 UTC
Hello,

While applying Measure Names filter using applyFilterAsync method of Worksheet object Extensions API throws following internal error:
![image](https://user-images.githubusercontent.com/96522947/147084185-1b22586b-9a84-42d8-b558-fc5a268516ec.png)

Bartosz

**Comment by johnDance** [comment] 2022-02-05 01:01
Hi @bartoszZamojcin 

This is actually a duplicate of https://github.com/tableau/extensions-api/issues/443. As the filter does its work, it uses the same selection implementation. Fixing that issue will also fix this issue.

Thanks,
John

**Comment by johnDance** [comment] 2022-02-05 01:02
Internal defect #1372577 (same as https://github.com/tableau/extensions-api/issues/443)

**Comment by johnDance** [comment] 2022-03-16 22:26
Hi @bartoszZamojcinRoche 
Like #443, has also been fixed in 2022.2. 
Thanks,
John

**Closed** 2022-10-06 17:05 UTC
Labels: Bug, Duplicate, Fixed, 2022.2
