### ISSUE TITLE
On IE11 initializeDialogAsync does not run

### ISSUE THREAD

**Issue by bggoxp** [tableau/extensions-api#215] opened 2019-04-16 14:18 UTC
I have an extension that opens a pop up on a click of a button. I open the pop up with 
(this extension uses react)
`window.tableau.extensions.ui.displayDialogAsync(popupUrl, payload, { height: 123, width: 123 })						.then(() => {...}).catch((error) => {...});`

And then in the componentDidMount function I call this:

`window.tableau.extensions.initializeDialogAsync().then(() => {
			...
		}).catch((error) => {
			...
		})`

In IE11 this initializeDialogAsync does not seem to be running as nothing inside it is called.
The HTML content of the page is loaded but anything done inside this call is not being displayed. Does anyone had this issue before or know how to handle this?

This exension works in Edge, Firefox and Chrome (the ones tested). Only IE is having this issue. It seems that it just ignores or cannot go inside the initializeDialogAsync

Many thanks in advance.

**Comment by johnDance** [comment] 2019-04-16 20:30
Hi
Can you open the debugger and see if there are messages in the console? Often this is caused by using something that IE11 doesn't support (like big arrow syntax above). We have polyfills for our code, but not for developer code.

Also, what version of Tableau are you running? IE11 got supported in 2018.3 or 2018.2.3.

Thanks,
John

**Comment by bggoxp** [comment] 2019-04-17 10:23
I get no errors on the console. I also use polyfill. The issue does not seem to be related to that.
The Tableau server version is 2018.2.3.

**Comment by johnDance** [comment] 2019-04-17 15:51
Are you willing to share your extension? Perhaps a cut down version without any specialized code that you are developing. We need to figure out what is happening on your end.
John

**Comment by bggoxp** [comment] 2019-04-17 16:03
Thanks once again.

I created a simple mockup app trying to recreate the scenario. It's just a quick draft and not fully functional, but it's very similar. 

On base.js you'll see that I'm opening the dialog but then, inside it,
 I can't access the tableau settings.

I leave here the app (it's a react app, just run `npm install` to get the node modules and `npm start` to start running)
[test--app.zip](https://github.com/tableau/extensions-api/files/3090484/test--app.zip)

Best regards,
Bruno

**Comment by johnDance** [comment] 2019-04-17 16:07
Thank you Bruno, we will investigate.
John

**Comment by bggoxp** [comment] 2019-04-17 16:11
Thank you very much. 
I'll just add that on my extension that's the part that works on all browsers but IE (version 11).

Looking forward for your feedback :)

**Comment by johnDance** [comment] 2019-04-18 22:05
Hi Bruno
There are two issues you might be running into here.
1. IE11 is very slow on the callback to componentDidMount after loading the extension. In my case (with a beefy machine), it can take 2 seconds. In Chrome it is called immediately.
2. The react-scripts module reloading does not call componentDidMount on refresh.

If you click to configure before 2 seconds, or after a change and auto-refresh, initializeAsync doesn't complete before attempting to call tableau.extensions.settings.set().

tableau.extensions is defined the minute you load the extensions library, but all of the namespaces under extensions are not set up until initializeAsync completes.

Hopefully that helps you get going on IE11.
John

**Comment by bggoxp** [comment] 2019-04-29 10:39
Hello John,

Sorry for the late answer, but I was on vacation.
Thank you very much for these suggestions, I'll have a look at it.

Best regards,
Bruno

**Comment by bggoxp** [comment] 2019-05-10 17:29
Hello @johnDance ,

I've experimented a bit more with the suggestion you gave and also with setting timeout functions.
I came to the conclusion that this is very inconsistent on IE. Sometimes with a timeout of a few seconds, the extension seems to work although, it's hit or miss because some other times it doesn't, there isn't a clear pattern.
Attached you'll see another test app that can be deployed in a tomcat server (for example) that just requires to install the node modules (npm install) and build the .war with mvn clean install.

This extension has a simple main screen that uses a timeout function to wait a bit before initializing the API, after that we can press the button to open a dialog. This dialog pops up and has a button to set a setting (window.tableau.extensions.settings.set) to set a variable and another to close. The expected behaviour is that the first button will set the variable but in IE this is not always the case. 

I debug this with the console always opened and I am seeing that in IE when trying to set it can't.

Do you have other insight on this matter?

Best regards,
Bruno

[iedebug.zip](https://github.com/tableau/extensions-api/files/3167468/iedebug.zip)

**Comment by craigbloodworth** [comment] 2019-06-24 16:08
I'm also finding this issue in a rework of my Export All extension. My configure component makes use of `useEffect()` as follows with '[Configure.js] useEffect' showing in the IE console, but tableau.extensions.initializeDialogAsync() does not fire:

```
console.log('[Configure.js] Initialise Config Screen', props);

  useEffect(() => {
    console.log('[Configure.js] useEffect');
    //Initialise Extension
    tableau.extensions.initializeDialogAsync().then((openPayload) => {

      console.log('[Configure.js] Initialise Dialog', openPayload);

      let sheetSettings = tableau.extensions.settings.get('selectedSheets');

      if (sheetSettings && sheetSettings != null) {
        console.log('[Configure.js] Existing Sheet Settings Found', sheetSettings);
        props.updateMeta(JSON.parse(sheetSettings));
      }

      let labelSettings = tableau.extensions.settings.get('buttonLabel');

      if (labelSettings && labelSettings != null) {
        console.log('[Configure.js] initializeDialogAsync Existing Label Settings Found', labelSettings);
        props.updateLabel(labelSettings);
      }

    });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);
```
And here's the IE11 console again showing no errors but not progressing with the initialisation either:
![image](https://user-images.githubusercontent.com/8116300/60034501-b65e1c00-96a2-11e9-954e-34e14e860fa6.png)

**Comment by bcantoni** [comment] 2022-01-05 01:29
Closing out based on age. If this is still an issue, please reopen with a comment on the latest status and we can revisit.

Also, in 2020 Tableau [officially stopped supporting IE11](https://www.tableau.com/about/blog/2020/6/upcoming-changes-tableau-operating-system-requirements), so these types of issues would probably not be fixed.

**Closed by bcantoni** 2022-01-05 01:29 UTC
