### ISSUE TITLE
WEBGL support in 2021.1 Mac version stopped working 

### ISSUE THREAD

**Issue by EdGonzalez-lovelytics** [tableau/extensions-api#378] opened 2021-04-14 14:18 UTC
Custom Extensions using WEBGL, i.e. Mapbox Maps,  are not working on the newest version of Tableau 2021.1.  These extensions work fine in previous Mac desktop versions.  

When we run debug mode we get the following message in the console:  "Failed to initialize WebGL"

**Comment by johnDance** [comment] 2021-04-14 18:28
Thank you for your report @EdGonzalez-lovelytics.
We have verified this internally. This was caused by the update to the latest version of QWebEngine/Chromium for the desktop browser. I have assigned a bug to the correct team. This will be a high priority to fix.
Thanks again,
John

**Comment by bcantoni** [comment] 2022-01-05 00:45
We don't expect this will be fixable, so I'll close as won't fix. Extensions support for WEBGL will work only for Tableau Server, not Desktop.

**Closed** 2022-12-29 17:23 UTC
Labels: Bug, Won't Fix
