### ISSUE TITLE
Tableau starts flickering with certain formatting settings in combination with any extension

### ISSUE THREAD

**Issue by merlijnbuit** [tableau/extensions-api#451] opened 2022-01-12 10:01 UTC
Hi,

I have been investigating an issue of one our customers, they reported that their dashboards started to flicker when they upgraded their Tableau Desktop environment on Mac (intel).

I compared on XML level the difference between a working and non working dashboard and found out that if you put a background color on the tiled container, the whole dashboard starts to bug and elements become invisible until you hover over them, and it keeps repeating itself. See attached video.

The behaviour disappears whenever you remove the background color from the tiled container.

**Version information:**
 - Tableau Desktop version: 2021.3
 - OS: Mac OS Monterey
 - Browser .
 - Version .

**Steps to reproduce (please include a code snippet, if possible):**
See video

https://user-images.githubusercontent.com/16118919/149118236-99eca620-5ed1-4535-b657-cc37bdb921ed.mov

**Comment by johnDance** [comment] 2022-01-12 19:13
Hi Merlijn
This is pretty crazy. Thanks for the video. I have reproduced the issue in 2021.3, but it looks like it was fixed in 2021.4 and (the upcoming) 2022.1. I've reached out to the team that would own this to see if they can give us any more information. I'll post more here when I get the reply.
John

**Comment by johnDance** [comment] 2022-01-14 21:52
Merlijn:
An update. The issue is not fixed in 2021.4 and 2022.1. It just takes a little more effort to manifest itself. The team is investigating the cause. I'll update again when I have more information.
John

**Comment by johnDance** [comment] 2022-01-14 22:09
Logged as defect #1364779

**Comment by johnDance** [comment] 2022-01-19 17:26
The issue manifests itself with QWebEngine software rendering. Right now, it looks like it is fixed in the upcoming 2022.2, but the team is still narrowing it down and investigating if it could be included in a maintenance release.

**Comment by johnDance** [comment] 2022-02-08 22:55
Hi Merlijn:
Just following up. This has been fixed in the upcoming 2022.2 because of an update to our internal Qt version. As I mentioned earlier, it still happens in 2021.4 and 2022.1, but appears to only happen with a WebPage object added to the dashboard. 

Meanwhile, there is a work-around, but becomes harder with the complexity of the dashboard. Do not have background tiled objects with color, just put them as filler around the extension and/or webpage zone. These can be colored without any problem.

John

**Closed** 2022-10-06 17:01 UTC
Labels: Bug, Fixed, 2022.2
