### ISSUE TITLE
Change in SummaryDataAsync when no data in sheet behavior changed

### ISSUE THREAD

**Issue by merlijnbuit** [tableau/extensions-api#339] opened 2020-07-14 11:56 UTC
Hi guys,

Below piece of code was working perfect until recent updates to the extensions API. This behavior is taking place on Tableau Server and not on Desktop. 

What we discovered recently?
When there is no summary data found in the sheet we normally would get an object with rows (0) and columns (0) meaning there is no data found in the sheet. But now we do not get anything anymore resulting in a crash and very ugly error message on server when certain filters or dashboard actions result in a empty sheet (which provides data to the extension). The 'then' in below example is not returning a single thing.

`return settings.selectedSheet
          .getSummaryDataAsync()
          .then(({ columns, data: rows }) => {
            if (columns.length === 0 && rows.length === 0) {
              throw new Error(
                "Summary data is empty. A filter is probably excluding all data."
              );
            }
          });`

Can you have a look at this please?

**Comment by SiebeG** [comment] 2020-07-14 12:00
Following this thread.

No data in the datasheet is not an error and can be a planned action. That's why we created a humane message. Throwing an error confuses the dashboard users.

**Comment by johnDance** [comment] 2020-07-14 19:31
Hi @merlijnbuit & @SiebeG 
This was a result of our moving to the new object model implementation inside Tableau. While the object model provides awesome advantages, we have found two issues in the implementation.
1. getSummaryData fails when there is no data
2. getSummaryData has a limit of 10,000 rows

The first issue (no data error) was fixed in Tableau 2020.2.2. @merlijnbuit - can you check your server version?
The second issue (10k limit) will be fixed in 2020.2.4, which will be released later this month.

Let us know if you have any questions.
Thanks!
John

**Comment by SiebeG** [comment] 2020-07-15 06:43
Hi @johnDance,

Thank you for your reply, really appreciated.
The error (instead of the message) when no data is available persists on Tableau Online (which is in our case version 2020.2.0)

![image](https://user-images.githubusercontent.com/64074494/87512135-c6aeb380-c676-11ea-8004-47fca0013fe5.png)

![image](https://user-images.githubusercontent.com/64074494/87512185-dcbc7400-c676-11ea-899f-60bd8b4b477d.png)

**Comment by johnDance** [comment] 2020-07-15 18:10
@SiebeG - Thank you for the clarification. I did some research and found that the fix didn't get integrated into online until the 2020.3 staging. That is coming out soon. Sorry for the confusion.  I'll update the fixes and timeline here:

getSummaryData fails when there is no data has been fixed in:
- desktop: 2020.2.2
- on-prem: 2020.2.2
- online: 2020.3

getSummaryData has a limit of 10,000 rows has been fixed in:
- desktop: 2020.2.4
- on-prem: 2020.2.4
- online: 2020.3

John

**Comment by SiebeG** [comment] 2020-07-16 05:54
Hi @johnDance thank you for the update, really appreciated.

I can confirm the fix for getSummaryData fail when there is no data is working in 2020.2.3 (not able to test on 2020.2.2).

Regards Siebe

**Comment by SiebeG** [comment] 2020-07-23 07:38
@johnDance still on track for releasing the bug fixes this month? A lot of customers are experiencing problems with the 10K issue as their analytics has become less valuable.

**Comment by SiebeG** [comment] 2020-07-24 08:49
Hi @benlower,

I hope this message is received in good health for you  and your loved ones. Can you confirm the updates are released in version 2020.2.4 (Desktop & Server) and 2020.3 (Online) and release date is in July as stated before in this thread by @johnDance ?

A lot of our customers are experiencing issues because of the 10K limit on summary data trasnfers by the Extensions API

Regards Siebe

**Comment by Kovner** [comment] 2020-07-24 17:58
@SiebeG , Yep the fix is in all of the next releases: 2020.2.4, 2020.3 Online and my understanding is that those will be released in July but that is pending all of the end-of-the-game activities that the release team does.

**Closed** 2022-01-05 00:53 UTC
Labels: Bug
